<?php

function gen_nav_bar() {
	echo '<nav class="navbar navbar-expand-lg navbar-light bg-light">'
 . '<a class="navbar-brand" href="index.php">Free Budget</a>'
 . '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">'
 .   '<span class="navbar-toggler-icon"></span>'
 .'</button>'
 .'<div class="collapse navbar-collapse" id="navbarNavDropdown">'
 .  '<ul class="navbar-nav">'
 .     '<li class="nav-item dropdown">'
 .       '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
 .         'Data entry'
 .       '</a>'
 .       '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
 .         '<a class="dropdown-item" href="#">Manual entry</a>'
 .         '<a class="dropdown-item" href="uploadTransactions.php">Import transactions</a>'
 .         '<a class="dropdown-item" href="">Resolve correlations</a>' /*TODO: number of correlations to resolve*/
 .       '</div>'
 .     '</li>'
 .     '<li class="nav-item dropdown">'
 .       '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
 .         'Create'
 .       '</a>'
 .       '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
 .         '<a class="dropdown-item" href="manageCategories.php">Create Categories</a>'
 .         '<a class="dropdown-item" href="createAccounts.php">Create Accounts</a>'
 .       '</div>'
 .     '</li>'
 .     '<li class="nav-item dropdown">'
 .       '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
 .         'Budget'
 .       '</a>'
 .       '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
 .         '<a class="dropdown-item" href="#">Manage Budgets</a>'
 .         '<a class="dropdown-item" href="#">Budget breakdown</a>'
 .       '</div>'
 .     '</li>'
 .     '<li class="nav-item dropdown">'
 .       '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'
 .         'Accounting'
 .       '</a>'
 .       '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
 .         '<a class="dropdown-item" href="#">Manage Books</a>'
 .         '<a class="dropdown-item" href="#">Accounting Ledger</a>'
 .         '<a class="dropdown-item" href="#">Accounting Journal</a>'
 .       '</div>'
 .     '</li>'
 .   '</ul>'
 . '</div>'
 .'</nav>';
}

?>